/* The following code was generated by JFlex 1.6.1 */

package Lexical_Analyzer;

import java_cup.runtime.Symbol;
import java.util.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>C:/Users/Diego Pérez Moir/Desktop/U/Sexto Ciclo/Compiladores/Lexical-Analyzer/Lexical-Analyzer/src/Lexical_Analyzer/Lexer.flex</tt>
 */
class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\0\1\6\1\0\1\0\1\0\22\0\1\0\1\52\1\25"+
    "\1\0\1\0\1\47\1\30\1\0\1\55\1\26\1\7\1\46\1\45"+
    "\1\24\1\22\1\5\1\2\11\1\1\0\1\44\1\50\1\43\1\51"+
    "\2\0\1\70\3\21\1\23\1\21\2\3\1\73\2\3\1\74\1\75"+
    "\1\67\1\3\1\71\1\3\1\72\1\37\4\3\1\20\2\3\1\53"+
    "\1\27\1\54\1\0\1\4\1\0\1\15\1\42\1\34\1\61\1\13"+
    "\1\14\1\62\1\63\1\35\1\3\1\66\1\16\1\41\1\33\1\36"+
    "\1\32\1\3\1\11\1\17\1\10\1\12\1\60\1\65\1\64\1\40"+
    "\1\3\1\56\1\31\1\57\1\0\6\0\1\0\32\0\1\0\23\0"+
    "\1\0\12\0\1\0\2\0\1\0\u15bd\0\1\0\u097f\0\13\0\35\0"+
    "\1\0\1\0\5\0\1\0\57\0\1\0\u0fa0\0\1\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\ud00f\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\2\1\1\2\1\3\1\4\5\2\1\5\1\6"+
    "\1\0\1\7\2\0\5\2\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\7\2\1\24\2\0\10\2\1\25\1\0\1\26\1\27"+
    "\3\2\1\30\4\2\1\31\1\32\1\33\1\34\1\35"+
    "\7\2\1\0\1\1\6\2\1\36\1\2\1\25\3\2"+
    "\1\37\6\2\1\40\3\2\1\24\1\0\1\41\1\42"+
    "\1\2\1\43\3\2\1\44\4\2\1\45\1\46\12\2"+
    "\1\47\2\2\1\50\1\2\1\51\1\2\1\52\3\2"+
    "\1\53\1\2\1\54\3\2\1\55\3\2\1\56\1\57"+
    "\11\2\1\60\1\2\1\61\1\2\1\62\3\2\1\63"+
    "\2\2\1\64\7\2\2\0\1\65";

  private static int [] zzUnpackAction() {
    int [] result = new int[181];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\76\0\174\0\272\0\370\0\370\0\u0136\0\u0174"+
    "\0\u01b2\0\u01f0\0\u022e\0\370\0\370\0\u026c\0\370\0\u02aa"+
    "\0\u02e8\0\u0326\0\u0364\0\u03a2\0\u03e0\0\u041e\0\u045c\0\370"+
    "\0\370\0\370\0\u049a\0\u04d8\0\u0516\0\u0554\0\370\0\370"+
    "\0\370\0\370\0\u0592\0\u05d0\0\u060e\0\u064c\0\u068a\0\u06c8"+
    "\0\u0706\0\u0744\0\u0782\0\u07c0\0\u07fe\0\u083c\0\u087a\0\u08b8"+
    "\0\u08f6\0\u0934\0\u0972\0\u09b0\0\370\0\u09ee\0\370\0\370"+
    "\0\u0a2c\0\u0a6a\0\u0aa8\0\272\0\u0ae6\0\u0b24\0\u0b62\0\u0ba0"+
    "\0\370\0\370\0\370\0\370\0\370\0\u0bde\0\u0c1c\0\u0c5a"+
    "\0\u0c98\0\u0cd6\0\u0d14\0\u0d52\0\u0d90\0\u07c0\0\u0dce\0\u0e0c"+
    "\0\u0e4a\0\u0e88\0\u0ec6\0\u0f04\0\272\0\u0f42\0\u026c\0\u0f80"+
    "\0\u0fbe\0\u0ffc\0\u103a\0\u1078\0\u10b6\0\u10f4\0\u1132\0\u1170"+
    "\0\u11ae\0\u11ec\0\u122a\0\u1268\0\u12a6\0\u12e4\0\u12e4\0\272"+
    "\0\272\0\u1322\0\272\0\u1360\0\u139e\0\u13dc\0\272\0\u141a"+
    "\0\u1458\0\u1496\0\u14d4\0\272\0\272\0\u1512\0\u1550\0\u158e"+
    "\0\u15cc\0\u160a\0\u1648\0\u1686\0\u16c4\0\u1702\0\u1740\0\272"+
    "\0\u177e\0\u17bc\0\272\0\u17fa\0\272\0\u1838\0\272\0\u1876"+
    "\0\u18b4\0\u18f2\0\272\0\u1930\0\272\0\u196e\0\u19ac\0\u19ea"+
    "\0\272\0\u1a28\0\u1a66\0\u1aa4\0\272\0\272\0\u1ae2\0\u1b20"+
    "\0\u1b5e\0\u1b9c\0\u1bda\0\u1c18\0\u1c56\0\u1c94\0\u1cd2\0\272"+
    "\0\u1d10\0\272\0\u1d4e\0\272\0\u1d8c\0\u1dca\0\u1e08\0\272"+
    "\0\u1e46\0\u1e84\0\272\0\u1ec2\0\u1f00\0\u1f3e\0\u1f7c\0\u1fba"+
    "\0\u1ff8\0\u2036\0\u2074\0\u20b2\0\370";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[181];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\0\1\2\1\3\1\4\1\0\1\5\1\0\1\6"+
    "\1\7\1\10\1\4\1\11\1\12\2\4\1\13\2\4"+
    "\1\14\1\4\1\15\1\16\1\17\1\0\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\4\4\1\26\1\27\1\0"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\1\42\1\43\1\44\3\4\1\45\1\4"+
    "\1\46\1\4\1\47\1\50\2\4\1\51\1\0\2\2"+
    "\17\0\1\52\54\0\2\53\15\0\1\54\1\0\1\52"+
    "\41\0\1\54\14\0\2\4\3\0\12\4\1\0\1\4"+
    "\6\0\11\4\15\0\16\4\101\0\2\4\3\0\1\4"+
    "\1\55\10\4\1\0\1\4\6\0\11\4\15\0\3\4"+
    "\1\56\12\4\3\0\2\4\3\0\3\4\1\57\6\4"+
    "\1\0\1\4\6\0\11\4\15\0\16\4\3\0\2\4"+
    "\3\0\6\4\1\60\3\4\1\0\1\4\6\0\11\4"+
    "\15\0\4\4\1\61\11\4\3\0\2\4\3\0\5\4"+
    "\1\62\4\4\1\0\1\4\6\0\4\4\1\63\4\4"+
    "\15\0\16\4\3\0\2\4\3\0\1\64\11\4\1\0"+
    "\1\4\6\0\11\4\15\0\16\4\6\16\1\0\16\16"+
    "\1\65\1\0\1\66\25\16\1\0\20\16\30\0\1\67"+
    "\76\0\1\70\47\0\2\4\3\0\2\4\1\71\7\4"+
    "\1\0\1\4\6\0\11\4\15\0\16\4\3\0\2\4"+
    "\3\0\2\4\1\72\7\4\1\0\1\4\6\0\11\4"+
    "\15\0\16\4\3\0\2\4\3\0\6\4\1\73\3\4"+
    "\1\0\1\4\6\0\11\4\15\0\16\4\3\0\2\4"+
    "\3\0\4\4\1\74\5\4\1\0\1\4\6\0\1\4"+
    "\1\75\5\4\1\76\1\4\15\0\16\4\3\0\2\4"+
    "\3\0\1\4\1\77\10\4\1\0\1\4\6\0\4\4"+
    "\1\100\4\4\15\0\16\4\43\0\1\101\75\0\1\102"+
    "\75\0\1\103\75\0\1\104\106\0\1\105\24\0\2\4"+
    "\3\0\12\4\1\0\1\4\6\0\4\4\1\106\4\4"+
    "\15\0\16\4\3\0\2\4\3\0\12\4\1\0\1\4"+
    "\6\0\4\4\1\107\4\4\15\0\16\4\3\0\2\4"+
    "\3\0\12\4\1\0\1\4\6\0\11\4\15\0\3\4"+
    "\1\110\12\4\3\0\2\4\3\0\3\4\1\111\6\4"+
    "\1\0\1\4\6\0\11\4\15\0\16\4\3\0\2\4"+
    "\3\0\1\4\1\112\10\4\1\0\1\4\6\0\11\4"+
    "\15\0\16\4\3\0\2\4\3\0\3\4\1\113\6\4"+
    "\1\0\1\4\6\0\11\4\15\0\16\4\3\0\2\4"+
    "\3\0\5\4\1\114\4\4\1\0\1\4\6\0\11\4"+
    "\15\0\16\4\1\0\2\52\10\0\1\115\7\0\1\115"+
    "\53\0\2\53\17\0\1\52\66\0\4\116\2\0\1\116"+
    "\1\0\1\116\10\0\2\116\3\0\2\116\16\0\1\116"+
    "\6\0\1\116\10\0\2\4\3\0\2\4\1\117\7\4"+
    "\1\0\1\4\6\0\11\4\15\0\16\4\3\0\2\4"+
    "\3\0\12\4\1\0\1\4\6\0\3\4\1\120\5\4"+
    "\15\0\16\4\3\0\2\4\3\0\1\121\11\4\1\0"+
    "\1\4\6\0\11\4\15\0\16\4\3\0\2\4\3\0"+
    "\7\4\1\122\2\4\1\0\1\4\6\0\11\4\15\0"+
    "\16\4\3\0\2\4\3\0\1\123\11\4\1\0\1\4"+
    "\6\0\11\4\15\0\16\4\3\0\2\4\3\0\6\4"+
    "\1\124\3\4\1\0\1\4\6\0\11\4\15\0\16\4"+
    "\3\0\2\4\3\0\1\4\1\125\10\4\1\0\1\4"+
    "\6\0\11\4\15\0\16\4\3\0\2\4\3\0\1\4"+
    "\1\126\10\4\1\0\1\4\6\0\11\4\15\0\16\4"+
    "\6\16\1\0\16\16\1\127\1\0\1\66\25\16\1\0"+
    "\20\16\3\0\2\4\3\0\12\4\1\0\1\4\6\0"+
    "\1\4\1\130\7\4\15\0\16\4\3\0\2\4\3\0"+
    "\6\4\1\131\3\4\1\0\1\4\6\0\11\4\15\0"+
    "\16\4\3\0\2\4\3\0\5\4\1\132\4\4\1\0"+
    "\1\4\6\0\11\4\15\0\16\4\3\0\2\4\3\0"+
    "\1\133\11\4\1\0\1\4\6\0\11\4\15\0\16\4"+
    "\3\0\2\4\3\0\12\4\1\0\1\4\6\0\1\134"+
    "\10\4\15\0\16\4\3\0\2\4\3\0\3\4\1\135"+
    "\6\4\1\0\1\4\6\0\11\4\15\0\16\4\3\0"+
    "\2\4\3\0\12\4\1\0\1\4\6\0\4\4\1\136"+
    "\4\4\15\0\16\4\3\0\2\4\3\0\12\4\1\0"+
    "\1\4\6\0\3\4\1\137\5\4\15\0\16\4\3\0"+
    "\2\4\3\0\2\4\1\140\7\4\1\0\1\4\6\0"+
    "\11\4\15\0\16\4\3\0\2\4\3\0\12\4\1\0"+
    "\1\4\6\0\3\4\1\141\5\4\15\0\16\4\3\0"+
    "\2\4\3\0\12\4\1\0\1\4\6\0\11\4\15\0"+
    "\5\4\1\142\10\4\3\0\2\4\3\0\12\4\1\0"+
    "\1\4\6\0\3\4\1\143\5\4\15\0\16\4\3\0"+
    "\2\4\3\0\5\4\1\144\4\4\1\0\1\4\6\0"+
    "\11\4\15\0\16\4\3\0\2\4\3\0\6\4\1\145"+
    "\3\4\1\0\1\4\6\0\11\4\15\0\16\4\1\0"+
    "\2\146\21\0\1\147\21\0\1\147\32\0\2\4\3\0"+
    "\3\4\1\150\6\4\1\0\1\4\6\0\11\4\15\0"+
    "\16\4\3\0\2\4\3\0\7\4\1\151\2\4\1\0"+
    "\1\4\6\0\11\4\15\0\16\4\3\0\2\4\3\0"+
    "\2\4\1\152\7\4\1\0\1\4\6\0\11\4\15\0"+
    "\16\4\3\0\2\4\3\0\3\4\1\153\6\4\1\0"+
    "\1\4\6\0\11\4\15\0\16\4\3\0\2\4\3\0"+
    "\3\4\1\154\6\4\1\0\1\4\6\0\11\4\15\0"+
    "\16\4\3\0\2\4\3\0\7\4\1\117\2\4\1\0"+
    "\1\4\6\0\11\4\15\0\16\4\3\0\2\4\3\0"+
    "\12\4\1\0\1\4\6\0\3\4\1\155\5\4\15\0"+
    "\16\4\3\0\2\4\3\0\12\4\1\0\1\4\6\0"+
    "\2\4\1\156\6\4\15\0\16\4\3\0\2\4\3\0"+
    "\6\4\1\157\3\4\1\0\1\4\6\0\11\4\15\0"+
    "\16\4\3\0\2\4\3\0\7\4\1\160\2\4\1\0"+
    "\1\4\6\0\11\4\15\0\16\4\3\0\2\4\3\0"+
    "\3\4\1\161\6\4\1\0\1\4\6\0\11\4\15\0"+
    "\16\4\3\0\2\4\3\0\6\4\1\162\3\4\1\0"+
    "\1\4\6\0\11\4\15\0\16\4\3\0\2\4\3\0"+
    "\5\4\1\163\4\4\1\0\1\4\6\0\11\4\15\0"+
    "\16\4\3\0\2\4\3\0\6\4\1\164\3\4\1\0"+
    "\1\4\6\0\11\4\15\0\16\4\3\0\2\4\3\0"+
    "\12\4\1\0\1\4\6\0\11\4\15\0\1\4\1\165"+
    "\14\4\3\0\2\4\3\0\12\4\1\0\1\4\6\0"+
    "\10\4\1\166\15\0\16\4\3\0\2\4\3\0\6\4"+
    "\1\167\3\4\1\0\1\4\6\0\11\4\15\0\16\4"+
    "\3\0\2\4\3\0\12\4\1\0\1\4\6\0\11\4"+
    "\15\0\10\4\1\170\5\4\3\0\2\4\3\0\12\4"+
    "\1\0\1\4\6\0\1\4\1\171\7\4\15\0\16\4"+
    "\3\0\2\4\3\0\12\4\1\0\1\4\6\0\11\4"+
    "\15\0\1\4\1\172\14\4\3\0\2\4\3\0\6\4"+
    "\1\173\3\4\1\0\1\4\6\0\11\4\15\0\16\4"+
    "\1\0\2\146\76\0\2\4\3\0\1\4\1\174\10\4"+
    "\1\0\1\4\6\0\11\4\15\0\16\4\3\0\2\4"+
    "\3\0\12\4\1\0\1\4\6\0\1\4\1\175\7\4"+
    "\15\0\16\4\3\0\2\4\3\0\12\4\1\0\1\4"+
    "\6\0\1\4\1\176\7\4\15\0\16\4\3\0\2\4"+
    "\3\0\1\177\11\4\1\0\1\4\6\0\11\4\15\0"+
    "\16\4\3\0\2\4\3\0\7\4\1\200\2\4\1\0"+
    "\1\4\6\0\11\4\15\0\16\4\3\0\2\4\3\0"+
    "\1\4\1\201\10\4\1\0\1\4\6\0\11\4\15\0"+
    "\16\4\3\0\2\4\3\0\3\4\1\202\6\4\1\0"+
    "\1\4\6\0\11\4\15\0\16\4\3\0\2\4\3\0"+
    "\12\4\1\0\1\4\6\0\11\4\15\0\6\4\1\203"+
    "\7\4\3\0\2\4\3\0\6\4\1\204\3\4\1\0"+
    "\1\4\6\0\11\4\15\0\16\4\3\0\2\4\3\0"+
    "\3\4\1\205\6\4\1\0\1\4\6\0\11\4\15\0"+
    "\16\4\3\0\2\4\3\0\1\4\1\206\10\4\1\0"+
    "\1\4\6\0\11\4\15\0\16\4\3\0\2\4\3\0"+
    "\1\207\11\4\1\0\1\4\6\0\11\4\15\0\16\4"+
    "\3\0\2\4\3\0\12\4\1\0\1\4\6\0\11\4"+
    "\15\0\13\4\1\210\1\211\1\4\3\0\2\4\3\0"+
    "\12\4\1\0\1\4\6\0\4\4\1\212\4\4\15\0"+
    "\16\4\3\0\2\4\3\0\12\4\1\0\1\4\6\0"+
    "\1\4\1\213\7\4\15\0\16\4\3\0\2\4\3\0"+
    "\12\4\1\0\1\4\6\0\11\4\15\0\1\4\1\214"+
    "\14\4\3\0\2\4\3\0\12\4\1\0\1\4\6\0"+
    "\11\4\15\0\2\4\1\215\13\4\3\0\2\4\3\0"+
    "\2\4\1\216\7\4\1\0\1\4\6\0\11\4\15\0"+
    "\16\4\3\0\2\4\3\0\4\4\1\217\5\4\1\0"+
    "\1\4\6\0\11\4\15\0\16\4\3\0\2\4\3\0"+
    "\12\4\1\0\1\4\6\0\7\4\1\220\1\4\15\0"+
    "\16\4\3\0\2\4\3\0\3\4\1\221\6\4\1\0"+
    "\1\4\6\0\11\4\15\0\16\4\3\0\2\4\3\0"+
    "\1\4\1\222\10\4\1\0\1\4\6\0\11\4\15\0"+
    "\16\4\3\0\2\4\3\0\12\4\1\0\1\4\6\0"+
    "\1\4\1\223\7\4\15\0\16\4\3\0\2\4\3\0"+
    "\12\4\1\0\1\4\6\0\3\4\1\224\5\4\15\0"+
    "\16\4\3\0\2\4\3\0\12\4\1\0\1\4\6\0"+
    "\2\4\1\225\6\4\15\0\16\4\3\0\2\4\3\0"+
    "\7\4\1\226\2\4\1\0\1\4\6\0\11\4\15\0"+
    "\16\4\3\0\2\4\3\0\5\4\1\227\4\4\1\0"+
    "\1\4\6\0\11\4\15\0\16\4\3\0\2\4\3\0"+
    "\5\4\1\230\4\4\1\0\1\4\6\0\11\4\15\0"+
    "\16\4\3\0\2\4\3\0\3\4\1\231\6\4\1\0"+
    "\1\4\6\0\11\4\15\0\16\4\3\0\2\4\3\0"+
    "\5\4\1\232\4\4\1\0\1\4\6\0\11\4\15\0"+
    "\16\4\3\0\2\4\3\0\1\233\11\4\1\0\1\4"+
    "\6\0\11\4\15\0\16\4\3\0\2\4\3\0\12\4"+
    "\1\0\1\4\6\0\1\4\1\234\7\4\15\0\16\4"+
    "\3\0\2\4\3\0\1\235\11\4\1\0\1\4\6\0"+
    "\11\4\15\0\16\4\3\0\2\4\3\0\12\4\1\0"+
    "\1\4\6\0\2\4\1\236\6\4\15\0\16\4\3\0"+
    "\2\4\3\0\12\4\1\0\1\4\6\0\1\4\1\237"+
    "\7\4\15\0\16\4\3\0\2\4\3\0\12\4\1\0"+
    "\1\4\6\0\6\4\1\240\2\4\15\0\16\4\3\0"+
    "\2\4\3\0\3\4\1\241\6\4\1\0\1\4\6\0"+
    "\11\4\15\0\16\4\3\0\2\4\3\0\3\4\1\242"+
    "\6\4\1\0\1\4\6\0\11\4\15\0\16\4\3\0"+
    "\2\4\3\0\12\4\1\0\1\4\6\0\3\4\1\243"+
    "\5\4\15\0\16\4\3\0\2\4\3\0\3\4\1\244"+
    "\6\4\1\0\1\4\6\0\11\4\15\0\16\4\3\0"+
    "\2\4\3\0\1\245\11\4\1\0\1\4\6\0\11\4"+
    "\15\0\16\4\3\0\2\4\3\0\12\4\1\0\1\4"+
    "\6\0\11\4\15\0\2\4\1\246\13\4\3\0\2\4"+
    "\3\0\12\4\1\0\1\4\6\0\4\4\1\247\4\4"+
    "\15\0\16\4\3\0\2\4\3\0\7\4\1\250\2\4"+
    "\1\0\1\4\6\0\11\4\15\0\16\4\3\0\2\4"+
    "\3\0\3\4\1\251\6\4\1\0\1\4\6\0\11\4"+
    "\15\0\16\4\3\0\2\4\3\0\12\4\1\0\1\4"+
    "\6\0\1\4\1\252\7\4\15\0\16\4\3\0\2\4"+
    "\3\0\1\4\1\253\10\4\1\0\1\4\6\0\11\4"+
    "\15\0\16\4\3\0\2\4\3\0\12\4\1\0\1\4"+
    "\6\0\5\4\1\254\3\4\15\0\16\4\3\0\2\4"+
    "\3\0\12\4\1\0\1\4\6\0\6\4\1\255\2\4"+
    "\15\0\16\4\3\0\2\4\3\0\12\4\1\0\1\4"+
    "\6\0\7\4\1\256\1\4\15\0\16\4\3\0\2\4"+
    "\3\0\12\4\1\0\1\4\6\0\10\4\1\257\15\0"+
    "\16\4\3\0\2\4\3\0\12\4\1\0\1\4\6\0"+
    "\4\4\1\260\4\4\15\0\16\4\3\0\2\4\3\0"+
    "\6\4\1\261\3\4\1\0\1\4\6\0\11\4\15\0"+
    "\16\4\3\0\2\4\3\0\7\4\1\262\2\4\1\0"+
    "\1\4\6\0\11\4\15\0\16\4\3\0\2\4\3\0"+
    "\12\4\1\0\1\4\6\0\11\4\1\263\14\0\16\4"+
    "\22\0\1\264\21\0\2\264\74\0\1\265\31\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[8432];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\3\1\2\11\5\1\2\11\1\0\1\11\2\0"+
    "\6\1\3\11\4\1\4\11\10\1\2\0\10\1\1\11"+
    "\1\0\2\11\10\1\5\11\7\1\1\0\31\1\1\0"+
    "\113\1\2\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[181];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    private Symbol symbol(int type, Object value){
        return new Symbol(type, yyline, yycolumn, value);
    }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 250) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { return new Symbol(sym.INTC, yytext());
            }
          case 54: break;
          case 2: 
            { return new Symbol(sym.ID, yytext());
            }
          case 55: break;
          case 3: 
            { return new Symbol(sym.DIV);
            }
          case 56: break;
          case 4: 
            { return new Symbol(sym.MULT);
            }
          case 57: break;
          case 5: 
            { return new Symbol(sym.POINT);
            }
          case 58: break;
          case 6: 
            { return new Symbol(sym.MINUS);
            }
          case 59: break;
          case 7: 
            { return new Symbol(sym.RPAREN);
            }
          case 60: break;
          case 8: 
            { return new Symbol(sym.EQUAL);
            }
          case 61: break;
          case 9: 
            { return new Symbol(sym.COMMA);
            }
          case 62: break;
          case 10: 
            { return new Symbol(sym.PLUS);
            }
          case 63: break;
          case 11: 
            { return new Symbol(sym.MOD);
            }
          case 64: break;
          case 12: 
            { return new Symbol(sym.LT);
            }
          case 65: break;
          case 13: 
            { return new Symbol(sym.GT);
            }
          case 66: break;
          case 14: 
            { return new Symbol(sym.NEG);
            }
          case 67: break;
          case 15: 
            { return new Symbol(sym.LBRACE);
            }
          case 68: break;
          case 16: 
            { return new Symbol(sym.RBRACE);
            }
          case 69: break;
          case 17: 
            { return new Symbol(sym.LPAREN);
            }
          case 70: break;
          case 18: 
            { return new Symbol(sym.LBRACKET);
            }
          case 71: break;
          case 19: 
            { return new Symbol(sym.RBRACKET);
            }
          case 72: break;
          case 20: 
            { return new Symbol(sym.DOUBLEC, yytext());
            }
          case 73: break;
          case 21: 
            { return new Symbol(sym.STRINGC, yytext());
            }
          case 74: break;
          case 22: 
            { return new Symbol(sym.AND);
            }
          case 75: break;
          case 23: 
            { return new Symbol(sym.OR);
            }
          case 76: break;
          case 24: 
            { return new Symbol(sym.IF);
            }
          case 77: break;
          case 25: 
            { return new Symbol(sym.CMP);
            }
          case 78: break;
          case 26: 
            { return new Symbol(sym.LTE);
            }
          case 79: break;
          case 27: 
            { return new Symbol(sym.GTE);
            }
          case 80: break;
          case 28: 
            { return new Symbol(sym.NEQ);
            }
          case 81: break;
          case 29: 
            { return new Symbol(sym.BRACES);
            }
          case 82: break;
          case 30: 
            { return new Symbol(sym.FOR);
            }
          case 83: break;
          case 31: 
            { return new Symbol(sym.INT);
            }
          case 84: break;
          case 32: 
            { return new Symbol(sym.NEW);
            }
          case 85: break;
          case 33: 
            { return new Symbol(sym.BOOLC, yytext());
            }
          case 86: break;
          case 34: 
            { return new Symbol(sym.THIS);
            }
          case 87: break;
          case 35: 
            { return new Symbol(sym.ELSE);
            }
          case 88: break;
          case 36: 
            { return new Symbol(sym.NULL);
            }
          case 89: break;
          case 37: 
            { return new Symbol(sym.BOOL);
            }
          case 90: break;
          case 38: 
            { return new Symbol(sym.VOID);
            }
          case 91: break;
          case 39: 
            { return new Symbol(sym.CLASS);
            }
          case 92: break;
          case 40: 
            { return new Symbol(sym.BREAK);
            }
          case 93: break;
          case 41: 
            { return new Symbol(sym.WHILE);
            }
          case 94: break;
          case 42: 
            { return new Symbol(sym.PRINT);
            }
          case 95: break;
          case 43: 
            { return new Symbol(sym.RETURN);
            }
          case 96: break;
          case 44: 
            { return new Symbol(sym.STRING);
            }
          case 97: break;
          case 45: 
            { return new Symbol(sym.DOUBLE);
            }
          case 98: break;
          case 46: 
            { return new Symbol(sym.MALLOC);
            }
          case 99: break;
          case 47: 
            { return new Symbol(sym.EXTENDS);
            }
          case 100: break;
          case 48: 
            { return new Symbol(sym.NEWARRAY);
            }
          case 101: break;
          case 49: 
            { return new Symbol(sym.READLINE);
            }
          case 102: break;
          case 50: 
            { return new Symbol(sym.INTERFACE);
            }
          case 103: break;
          case 51: 
            { return new Symbol(sym.IMPLEMENTS);
            }
          case 104: break;
          case 52: 
            { return new Symbol(sym.READINT);
            }
          case 105: break;
          case 53: 
            { return new Symbol(sym.SEMICOLON);
            }
          case 106: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
