
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Oct 08 00:41:20 CST 2018
//----------------------------------------------------

package Lexical_Analyzer;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LTE = 18;
  public static final int READLINE = 47;
  public static final int LBRACKET = 9;
  public static final int MULT = 5;
  public static final int READINT = 46;
  public static final int BRACES = 26;
  public static final int STRINGC = 53;
  public static final int DOUBLE = 28;
  public static final int LPAREN = 11;
  public static final int INTERFACE = 35;
  public static final int INT = 27;
  public static final int FOR = 39;
  public static final int MINUS = 4;
  public static final int CMP = 21;
  public static final int RPAREN = 12;
  public static final int SEMICOLON = 3;
  public static final int AND = 23;
  public static final int LT = 17;
  public static final int OR = 24;
  public static final int BOOL = 29;
  public static final int COMMA = 7;
  public static final int CLASS = 32;
  public static final int DIV = 6;
  public static final int NEWARRAY = 45;
  public static final int PLUS = 2;
  public static final int IF = 36;
  public static final int GETBYTE = 49;
  public static final int THIS = 43;
  public static final int ID = 52;
  public static final int SETBYTE = 50;
  public static final int EOF = 0;
  public static final int RETURN = 40;
  public static final int RBRACKET = 10;
  public static final int EQUAL = 15;
  public static final int NEW = 44;
  public static final int error = 1;
  public static final int NULL = 51;
  public static final int MOD = 16;
  public static final int NEQ = 22;
  public static final int BREAK = 41;
  public static final int VOID = 31;
  public static final int GTE = 20;
  public static final int NEG = 25;
  public static final int BOOLC = 56;
  public static final int ELSE = 37;
  public static final int LBRACE = 13;
  public static final int POINT = 8;
  public static final int DOUBLEC = 55;
  public static final int WHILE = 38;
  public static final int RBRACE = 14;
  public static final int INTC = 54;
  public static final int EXTENDS = 33;
  public static final int STRING = 30;
  public static final int MALLOC = 48;
  public static final int IMPLEMENTS = 34;
  public static final int GT = 19;
  public static final int PRINT = 42;
}

