
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Nov 22 14:58:10 CST 2018
//----------------------------------------------------

package Lexical_Analyzer;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LTE = 19;
  public static final int READLINE = 50;
  public static final int LBRACKET = 10;
  public static final int MULT = 5;
  public static final int CONST = 55;
  public static final int READINT = 49;
  public static final int BRACES = 27;
  public static final int STRINGC = 57;
  public static final int DOUBLE = 31;
  public static final int LPAREN = 12;
  public static final int INTERFACE = 38;
  public static final int INT = 30;
  public static final int FOR = 42;
  public static final int MINUS = 4;
  public static final int CMP = 22;
  public static final int RPAREN = 13;
  public static final int SEMICOLON = 3;
  public static final int AND = 24;
  public static final int INCLUDES = 29;
  public static final int LT = 18;
  public static final int OR = 25;
  public static final int BOOL = 32;
  public static final int COMMA = 7;
  public static final int CLASS = 35;
  public static final int DIV = 6;
  public static final int NEWARRAY = 48;
  public static final int PLUS = 2;
  public static final int IF = 39;
  public static final int GETBYTE = 52;
  public static final int THIS = 46;
  public static final int ID = 56;
  public static final int SETBYTE = 53;
  public static final int EOF = 0;
  public static final int RETURN = 43;
  public static final int RBRACKET = 11;
  public static final int EQUAL = 16;
  public static final int NEW = 47;
  public static final int error = 1;
  public static final int NULL = 54;
  public static final int MOD = 17;
  public static final int NEQ = 23;
  public static final int BREAK = 44;
  public static final int VOID = 34;
  public static final int GTE = 21;
  public static final int FILENAME = 58;
  public static final int NEG = 26;
  public static final int BOOLC = 61;
  public static final int ELSE = 40;
  public static final int LBRACE = 14;
  public static final int SHARP = 9;
  public static final int POINT = 8;
  public static final int DOUBLEC = 60;
  public static final int WHILE = 41;
  public static final int RBRACE = 15;
  public static final int INTC = 59;
  public static final int EXTENDS = 36;
  public static final int PARENS = 28;
  public static final int STRING = 33;
  public static final int MALLOC = 51;
  public static final int IMPLEMENTS = 37;
  public static final int GT = 20;
  public static final int PRINT = 45;
}

